version: '3.7'

services:
  webpack:
    image: node:12.8.1
    user: "1000"
    volumes:
      - ../frontend:/usr/local/app/frontend
      - ../backend/public:/usr/local/app/backend/public
    working_dir: "/usr/local/app/frontend"
    command: sh "./_scripts/run"
